import type { Metadata } from "next";
import "antd/dist/reset.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import Providers from "./providers";
import SearchBar from "@/features/search/components/SearchBar";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lystio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable}`}>
        <Providers>
          <SearchBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
